version: '3.8'

services:
  mcp-proxy:
    build:
      context: ./mcp-proxy
      dockerfile: Dockerfile
    container_name: mcp-proxy
    ports:
      - "${MCP_PORT}:8000"
    volumes:
      - "${MCP_CONFIG_PATH}:/app/config/mcp-config.json"
    command: ["mcpo", "--host", "0.0.0.0", "--port", "${MCP_PORT}", "--config", "/app/config/mcp-config.json"]
    restart: unless-stopped

  tools:
    image: ghcr.io/mcptools/mcp-tools:latest
    profiles: ["tools"]
    container_name: mcp-tools
    restart: unless-stopped
